version: 2.1

orbs:
  # orb under test
  asdf: {}
  # changelog: https://github.com/CircleCI-Public/BATS-orb/releases
  bats: circleci/bats@1.1.0
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.1.0
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/rynkowsg
  rynkowsg: rynkowsg/rynkowsg@0.3.0

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test_install_asdf:
    executor: <<parameters.executor>>
    parameters:
      # parameters copied from install_asdf
      debug:
        type: boolean
        default: false
        description: "Flag to run the script in debug mode."
      executor: {type: executor}
      install_dir:
        type: string
        default: ""
        description: "Destination where to install the tool. ASDF_DIR is set to that value. By defaults takes ~/.asdf."
      version:
        type: string
        default: ""
        description:
          Requested version. If not provided it install the latest.
    steps:
      - checkout
      - rynkowsg-orb/install_asdf:
          debug: << parameters.debug >>
          install_dir: << parameters.install_dir >>
          version: << parameters.version >>
      - run:
          name: "test command: asdf"
          command: asdf --version

  test_install:
    parameters:
      debug: {type: boolean, default: false}
      executor: {type: executor}
    executor: <<parameters.executor>>
    steps:
      - asdf/install:
          debug: <<parameters.debug>>
      - run:
          name: Check
          command: asdf --version

workflows:
  test-deploy:
    jobs:
      - test_install:
          name: "test_install; E:<<matrix.executor>>"
          debug: false
          matrix:
            parameters:
              executor:
                - rynkowsg/docker_arm_cimg_base
                - rynkowsg/docker_x86_cimg_base
                - rynkowsg/machine_x86_android
                - rynkowsg/machine_arm_ubuntu2204
                - rynkowsg/machine_x86_ubuntu2204
                - rynkowsg/macos
          filters: *filters

      - orb-tools/pack:
          requires:
            - test_install
          filters: *filters

      - orb-tools/publish:
          name: publish-dev
          orb_name: rynkowsg/asdf
          vcs_type: <<pipeline.project.type>>
          pub_type: dev
          requires:
            - orb-tools/pack
          context: circleci/orb-publishing-context
          filters: *filters

      - orb-tools/publish:
          name: publish-prod
          orb_name: rynkowsg/asdf
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          requires:
            - publish-dev
          context: circleci/orb-publishing-context
          filters: *release-filters
